CONFIG_ENABLE_VFS=y
CONFIG_PROCFS=y
CONFIG_THREAD_STATS=y
CONFIG_ENABLE_NET=y
CONFIG_KERNEL_ASYNC=y
CONFIG_ENABLE_WLAN=y
CONFIG_SD_CARD=y
CONFIG_FATFS=y
CONFIG_I2S=y
CONFIG_SPI_CORE=y
CONFIG_I2C_CORE=y
CONFIG_LCD=y
CONFIG_CO5300=y
CONFIG_CO5300_PANEL_216INCH=y
CONFIG_CST9220=y
CONFIG_QMI8658=y
CONFIG_BATTERY=y
CONFIG_ESP32_INTERNAL_FLASH=y
CONFIG_ESP32_FLASH_IO_REGION_BASE=0x00800000
CONFIG_ESP32_FLASH_IO_REGION_SIZE=0x00800000

CONFIG_NET_STATIC_IP="10.171.198.11"
CONFIG_NET_ROUTER_IP="10.171.198.28"
CONFIG_WLAN_SSID="bluekernel1"
CONFIG_WLAN_PASSWORD="12345678"
