#!/usr/bin/env python3
"""Convert downloaded website artwork and subset its Chinese sample font.

Requires Pillow and fonttools. See assets/SOURCES.md for the original download URLs.
Generated images and font are checked in; firmware builds do not require this script.
"""

import argparse
from pathlib import Path
import shutil

from PIL import Image, ImageDraw, ImageFont
from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source_dir", type=Path)
    args = parser.parse_args()
    assets = Path(__file__).resolve().parents[1] / "assets"
    website = assets / "website"
    with Image.open(args.source_dir / "banner.jpg") as source:
        image = source.convert("RGB").crop((1100, 80, 2260, 1130))
        image.thumbnail((360, 326), Image.Resampling.LANCZOS)
        image.save(website / "10-banner.png", compress_level=6)

    # Reflow peer boxes from the official architecture diagram without changing labels.
    # Coordinates refer to a 2048x944 preview; crops use the original full resolution.
    heading_font = ImageFont.truetype(str(args.source_dir / "NotoSansSC.ttf"), 24)
    heading_font.set_variation_by_axes([600])
    with Image.open(args.source_dir / "architecture.jpg") as source:
        source = source.convert("RGB")

        def box(rect, size):
            x0, y0, x1, y1 = rect
            crop = source.crop((round(x0 * source.width / 2048),
                                round(y0 * source.height / 944),
                                round(x1 * source.width / 2048),
                                round(y1 * source.height / 944)))
            return crop.resize(size, Image.Resampling.LANCZOS)

        def canvas(title):
            result = Image.new("RGB", (360, 326), "#1e2863")
            ImageDraw.Draw(result).text((180, 6), title, font=heading_font,
                                        fill="#e4eaff", anchor="mt")
            return result

        image = canvas("内核核心")
        for index in range(9):
            row, column = divmod(index, 3)
            tile = box((50 + column * 159, 390 + row * 50,
                        205 + column * 159, 435 + row * 50), (174, 48))
            x = 93 if index == 8 else 3 + index % 2 * 180
            image.paste(tile, (x, 49 + index // 2 * 54))
        image.save(website / "11-architecture.png", compress_level=6)

        image = canvas("文件系统")
        draw = ImageDraw.Draw(image)
        draw.rounded_rectangle((8, 59, 351, 117), radius=8, fill="#2c40a4")
        draw.text((180, 70), "虚拟文件系统 VFS", font=heading_font,
                  fill="#e4eaff", anchor="mt")
        for index in range(6):
            tile = box((563 + index * 108, 467, 668 + index * 108, 535), (112, 73))
            image.paste(tile, (4 + index % 3 * 120, 145 + index // 3 * 84))
        image.save(website / "12-filesystem.png", compress_level=6)

        image = canvas("平台与芯片架构")
        image.paste(box((50, 618, 283, 663), (332, 50)), (14, 52))
        image.paste(box((290, 618, 523, 663), (332, 50)), (14, 110))
        for index in range(4):
            tile = box((50 + index * 119, 739, 165 + index * 119, 784), (166, 58))
            image.paste(tile, (8 + index % 2 * 178, 187 + index // 2 * 70))
        image.save(website / "13-platform.png", compress_level=6)

    text = "".join(path.read_text(encoding="utf-8") for path in sorted(website.glob("*.txt")))
    font = TTFont(args.source_dir / "NotoSansSC.ttf")
    font = instantiateVariableFont(font, {"wght": 400}, inplace=True)
    options = subset.Options()
    options.name_IDs = [0, 1, 2, 3, 4, 5, 6, 13, 14]
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(text=text + "".join(map(chr, range(32, 127))) + "…●�")
    subsetter.subset(font)
    names = {
        1: "BlueOS Website Text",
        2: "Regular",
        3: "BlueOS Website Text Regular subset 2026-09-08",
        4: "BlueOS Website Text Regular",
        6: "BlueOSWebsiteText-Regular",
    }
    for record in font["name"].names:
        if record.nameID in names:
            record.string = names[record.nameID].encode(record.getEncoding())
    font.save(assets / "website-text.ttf")
    shutil.copyfile(args.source_dir / "OFL.txt", assets / "FONT-LICENSE.txt")
    glyphs = "".join(sorted({char for char in text if ord(char) > 127}))
    (assets / "website-glyphs.slint").write_text(
        '// Generated by tools/prepare_website_assets.py; do not edit.\n'
        'export global WebsiteGlyphs {\n'
        f'    out property <string> characters: "{glyphs}";\n'
        '}\n', encoding="utf-8")
    # Match pagination to the actual regular font, not ASCII/CJK character-count guesses.
    cmap = font.getBestCmap()
    widths = [(code, font["hmtx"][glyph][0]) for code, glyph in sorted(cmap.items())]
    metrics = '// Generated by tools/prepare_website_assets.py; do not edit.\n'
    metrics += f'pub const UNITS_PER_EM: u32 = {font["head"].unitsPerEm};\n'
    metrics += 'pub const ADVANCES: &[(u32, u32)] = &[\n'
    metrics += ''.join(f'    ({code}, {width}),\n' for code, width in widths)
    metrics += '];\n'
    (assets / "text-metrics.rs").write_text(metrics, encoding="utf-8")
    print(f"Embedded font: {len(glyphs)} non-ASCII characters")
    for path in sorted(website.glob("*.png")):
        with Image.open(path) as image:
            print(path.name, image.size, path.stat().st_size)


if __name__ == "__main__":
    main()
