// Copyright (c) 2026 vivo Mobile Communication Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Material Symbols Rounded code points included in blueos-icons.ttf.
export global Icons {
    out property <string> monitoring: "\u{f190}";
    out property <string> file-io: "\u{e2c7}";
    out property <string> palette: "\u{e40a}";
    out property <string> brightness: "\u{e3ab}";
    out property <string> wifi: "\u{eb31}";
    out property <string> sensors: "\u{e51e}";
    out property <string> sd-card: "\u{e623}";
    out property <string> download: "\u{e2c0}";
    out property <string> music: "\u{e405}";
    out property <string> home: "\u{e9b2}";
    out property <string> back: "\u{e5de}";
    out property <string> gyroscope: "\u{e84d}";
    out property <string> touch: "\u{e913}";
    out property <string> power: "\u{f8c7}";
}
